@startuml
skinparam defaultFontName Courier
skinparam component {
  BackgroundColor White
  BorderColor Black
}

title **SysML IBD: Luftdruck-Sensor System**\nInternal Block Diagram -- non-blocking Datenfluesse

component "STM32F411VET6\n(MCU)" as MCU {

  component "main.c\n(Hauptprogramm)" as MAIN {
    [SystemClock]
    [GPIO_Init]
    [I2C1_Init]
    [MainLoop]
    [ExtiCallback]
  }

  component "BMP180 Treiber\n(bmp180.c/h)" as DRV {
    (BMP180_Start)
    (BMP180_GetTemp)
    (BMP180_GetPress)
    (BMP180_GetAlt)
  }

  component "7-Segment\n(SiebenSeg.c/h)" as SEG {
    (Segment a..g + DP)
    (Digit 0..3)
  }

  component "Test-SW\n(test_bmp180.c/h)" as TEST {
    (Chip-ID pruefen)
    (Messzyklus)
  }
}

component "Peripherie" as PERIPH {

  component "GY-BMP180" as BMP {
    () "I2C Addr 0xEE"
  }

  component "7-Segment-Anzeige" as DISPLAY {
    () "Segmentsignale"
    () "Digit-Signale"
  }

  component "Taster" as BUTTONS {
    () "PD1 (EXTI1)"
    () "PD2 (EXTI2)"
  }
}

component "Interrupts" as IRQ {

  component "SysTick\n(1 ms)" as SYSTICK {
    [HAL_IncTick]
    [HAL_SYSTICK_Hook]
  }

  component "EXTI1\n(Button1)" as EXTI1 {
    [HAL_GPIO_EXTI_Callback]
  }

  component "EXTI2\n(Button2)" as EXTI2 {
    [HAL_GPIO_EXTI_Callback]
  }
}

' Datenfluesse
I2C1_Init --> DRV : HAL_I2C_Mem_Read/Write (100 kHz)
DRV --> BMP : I2C-Bus (SDA/SCL)
BMP --> DRV : Messdaten (UT, UP)

MainLoop --> DRV : Sensor-Lesung (alle 500 ms)
DRV --> MainLoop : Temperatur, Druck, Hoehe
MainLoop --> SEG : Display-Update (alle 10 ms)
SEG --> DISPLAY : GPIO Signale

BUTTONS --> EXTI1 : Falling Edge PD1
BUTTONS --> EXTI2 : Falling Edge PD2
EXTI1 --> ExtiCallback : DispMode aendern
EXTI2 --> ExtiCallback : DispMode zyklisch
ExtiCallback --> MainLoop : DispMode (volatile)

SYSTICK --> SEG : Multiplexing (1 ms)
SYSTICK --> MainLoop : HAL_GetTick()

MainLoop --> TEST : optional aktivieren
TEST --> BMP : Chip-ID pruefen (0x55)

@enduml
